ORGE_TOP = ../../..

.PHONY: clean clean-word-sets

include $(ORGE_TOP)/GNUmakesettings.inc

clean: clean-word-sets

clean-word-sets:
	@/bin/rm -f *-words.txt *-names.txt *-surnames.txt *-placenames.txt
