ORGE_TOP = ../..


MODULES_DIRS = appendices elements general implementation narrative


info-local:
	@echo "  To generate following documents, go to the specified directory and run 'make full-doc':"
	@echo "    - for OrgeServers.pdf, go to ../code/servers/doc"
	@echo "    - for Orge-game-system.pdf, go to ../../doc"
	

include $(ORGE_TOP)/GNUmakerules.inc
