ORGE_TOP = ../..


MODULES_DIRS = aging appendices experience modifiers


include $(ORGE_TOP)/GNUmakerules.inc


info-local:
	@echo "Go to osdl/Orge/trunk/src/code/servers/doc to generate OrgeServers.pdf"
	
	
