ORGE_TOP = ../..


MODULES_DIRS = appendices elements general implementation narrative


info-local:
	@echo "  Go to osdl/Orge/trunk/src/code/servers/doc to generate OrgeServers.pdf"
	@echo "  Go to osdl/Orge/trunk/doc to generate Orge-game-system.pdf (use: 'make full-doc')"
	

include $(ORGE_TOP)/GNUmakerules.inc
